#Start with a base image containing Java runtime
FROM openjdk:17

#Add Maintainer Info
LABEL maintainer="yndarane@gmail.com"

#Add a volume pointing to optinal
VOLUME /opt/

#Make port 8080 available to the world outside this container
EXPOSE 8080
ADD target/solarRecommendation-0.0.1-SNAPSHOT.jar springboot-docker-demo.jar
#The application's jar file
#ARG JAR_FILE=target/spring-boot-app-1.0.0.jar

#Add the application's jar to the container
#ADD ${JAR_FILE} app.jar

#Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar","springboot-docker-demo.jar"]